/**
 * IPC permission audit — whitelist of channels and what they may do.
 */

import { IPC_CHANNELS, type IpcChannel } from '@shared/constants/ipc-channels';

export type IpcPermission =
  | 'read_app_info'
  | 'read_managed_paths'
  | 'open_managed_folder'
  | 'open_bundled_guide'
  | 'read_security_health'
  | 'manage_google_accounts'
  | 'manage_projects'
  | 'import_novels'
  | 'manage_terms'
  | 'manage_memory'
  | 'build_translation_pack'
  | 'manage_notebook'
  | 'send_gemini_translation'
  | 'manage_jobs'
  | 'export'
  | 'manage_diagnostics'
  | 'manage_setup'
  | 'manage_ai_providers'
  | 'manage_khepree_access';

export interface IpcChannelAudit {
  channel: IpcChannel;
  permission: IpcPermission;
  allowsFilesystem: boolean;
  allowsShell: boolean;
  allowsDbQuery: boolean;
  allowsSecrets: false;
  notes: string;
}

const noSecrets = false as const;

function accountChannel(
  channel: IpcChannel,
  notes: string,
): IpcChannelAudit {
  return {
    channel,
    permission: 'manage_google_accounts',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes,
  };
}

export const IPC_CHANNEL_AUDIT: readonly IpcChannelAudit[] = [
  {
    channel: IPC_CHANNELS.APP_PING,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Health ping only',
  },
  {
    channel: IPC_CHANNELS.APP_GET_VERSION,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'App name/version',
  },
  {
    channel: IPC_CHANNELS.APP_GET_INFO,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Platform/runtime metadata',
  },
  {
    channel: IPC_CHANNELS.APP_GET_PATHS,
    permission: 'read_managed_paths',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Returns managed AppData paths only — no arbitrary path input',
  },
  {
    channel: IPC_CHANNELS.APP_OPEN_FOLDER,
    permission: 'open_managed_folder',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes:
      'shell.openPath only for enum pathKey under managed Khepree Novel AI dirs; rejects outside paths',
  },
  {
    channel: IPC_CHANNELS.APP_OPEN_OFFICIAL_CONTACT,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes:
      'shell.openExternal for canonical Khepree Labs official contact channels only; channel id resolved in main',
  },
  {
    channel: IPC_CHANNELS.SECURITY_HEALTH_CHECK,
    permission: 'read_security_health',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'safeStorage availability only — never returns ciphertext or tokens',
  },
  accountChannel(IPC_CHANNELS.ACCOUNT_LIST, 'List Google accounts (DTO only)'),
  accountChannel(IPC_CHANNELS.ACCOUNT_GET, 'Get one account by UUID'),
  accountChannel(
    IPC_CHANNELS.ACCOUNT_ADD,
    'Create account + dedicated Playwright profile; may open browser',
  ),
  accountChannel(IPC_CHANNELS.ACCOUNT_RENAME, 'Rename account label'),
  accountChannel(IPC_CHANNELS.ACCOUNT_SET_PLAN, 'Set plan enum manually'),
  accountChannel(IPC_CHANNELS.ACCOUNT_SET_NOTES, 'Update notes'),
  accountChannel(
    IPC_CHANNELS.ACCOUNT_OPEN_BROWSER,
    'Open headed Playwright for account profile (locked userDataDir)',
  ),
  accountChannel(IPC_CHANNELS.ACCOUNT_CLOSE_BROWSER, 'Close Playwright session'),
  accountChannel(IPC_CHANNELS.ACCOUNT_TEST_SESSION, 'Probe session usability'),
  accountChannel(
    IPC_CHANNELS.ACCOUNT_COMPLETE_LOGIN,
    'Finalize login after manual Google auth; optional email/label',
  ),
  accountChannel(IPC_CHANNELS.ACCOUNT_DISABLE, 'Disable worker'),
  accountChannel(IPC_CHANNELS.ACCOUNT_ENABLE, 'Enable worker'),
  accountChannel(
    IPC_CHANNELS.ACCOUNT_REMOVE,
    'Delete account requires confirm:true; removes profile dir',
  ),
  {
    channel: IPC_CHANNELS.PROJECT_LIST,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List projects from SQLite',
  },
  {
    channel: IPC_CHANNELS.PROJECT_CREATE,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Create empty project row',
  },
  {
    channel: IPC_CHANNELS.PROJECT_UPDATE_LANGUAGES,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Update project source/target language pair',
  },
  {
    channel: IPC_CHANNELS.PROJECT_REDETECT_SOURCE_LANGUAGE,
    permission: 'manage_projects',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Re-detect project source language from chapter content',
  },
  {
    channel: IPC_CHANNELS.EDITION_LIST,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List translation editions for a project',
  },
  {
    channel: IPC_CHANNELS.EDITION_CREATE,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Create target-language edition (no source re-import)',
  },
  {
    channel: IPC_CHANNELS.EDITION_SWITCH,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Switch active translation edition',
  },
  {
    channel: IPC_CHANNELS.LANGUAGE_LIST,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'List LanguageProfile registry',
  },
  {
    channel: IPC_CHANNELS.LANGUAGE_DETECT,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Heuristic (+ optional AI) language detection from sample',
  },
  {
    channel: IPC_CHANNELS.TRANSLATION_SETTINGS_GET,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read global translation settings (default target language)',
  },
  {
    channel: IPC_CHANNELS.TRANSLATION_SETTINGS_SET_DEFAULT_TARGET,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Set global default target language for new projects/editions',
  },
  {
    channel: IPC_CHANNELS.PROJECT_GET,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Get one project by id',
  },
  {
    channel: IPC_CHANNELS.PROJECT_DELETE,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Soft-delete project; stop source watcher; cancel active jobs',
  },
  {
    channel: IPC_CHANNELS.PROJECT_RESOLVE_WORKER,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Resolve canonical Google worker for a project (never first READY)',
  },
  {
    channel: IPC_CHANNELS.PROJECT_SET_WORKER,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Assign project worker + ensure Translation Notebook',
  },
  {
    channel: IPC_CHANNELS.PROJECT_GET_TRANSLATE_PACK_SETTINGS,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read preferNotebookPack from project style_config',
  },
  {
    channel: IPC_CHANNELS.PROJECT_SET_PREFER_NOTEBOOK_PACK,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Update preferNotebookPack in project style_config',
  },
  {
    channel: IPC_CHANNELS.PROJECT_SET_PRIMARY_PROVIDER,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Set or clear project primary translation AI provider override',
  },
  {
    channel: IPC_CHANNELS.PROJECT_SET_AI_PREFERENCE,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Set project AI routing preference (global override or per-project)',
  },
  {
    channel: IPC_CHANNELS.IMPORT_SELECT_FILE,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Native open dialog for txt/epub/docx only; returns chosen path',
  },
  {
    channel: IPC_CHANNELS.IMPORT_PREVIEW,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Parse file + chapter detect; no DB write; no translation',
  },
  {
    channel: IPC_CHANNELS.IMPORT_UPDATE_PREVIEW,
    permission: 'import_novels',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Manual split / title patches on in-memory preview',
  },
  {
    channel: IPC_CHANNELS.IMPORT_COMMIT,
    permission: 'import_novels',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Persist chapters/paragraphs + source hashes; no translation',
  },
  {
    channel: IPC_CHANNELS.IMPORT_DISCARD,
    permission: 'import_novels',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Drop in-memory preview session',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_SELECT_FOLDER,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Native open dialog for source folder',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_SCAN_PREVIEW,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Scan folder preview before project create',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_SCAN,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Rescan project source folder and diff against DB',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_DETECT_LANGUAGE,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Detect source language from folder preview sample',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_IMPORT,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Import chapters from folder preview or incremental import',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_GET_STATUS,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Source folder status summary for project',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_UPDATE_SETTINGS,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Update folder watch and auto-import settings',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_CHANGE_FOLDER,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Change or preview new source folder path',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_RESOLVE_CONFLICT,
    permission: 'import_novels',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Pick canonical file for duplicate chapter number',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_MARK_RETRANSLATE,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Mark chapter needs retranslation after source change',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_GET_DIFF,
    permission: 'manage_projects',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Text diff between stored and file source',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_OPEN_FOLDER,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Open project source folder in shell',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_CANCEL_SCAN,
    permission: 'import_novels',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Abort in-flight folder scan',
  },
  {
    channel: IPC_CHANNELS.SOURCE_FOLDER_ON_SCAN_PROGRESS,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Main→renderer push events for folder scan/notifications',
  },
  {
    channel: IPC_CHANNELS.BOOK_METADATA_GET,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read project book metadata',
  },
  {
    channel: IPC_CHANNELS.BOOK_METADATA_UPDATE,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Update project book metadata',
  },
  {
    channel: IPC_CHANNELS.BOOK_METADATA_LIST_DOCUMENTS,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List project auxiliary documents',
  },
  {
    channel: IPC_CHANNELS.BOOK_METADATA_SYNC_PROFILE,
    permission: 'manage_projects',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Sync 00_BOOK_PROFILE.md to Drive',
  },
  {
    channel: IPC_CHANNELS.TERM_SEARCH,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Search term vault with filters',
  },
  {
    channel: IPC_CHANNELS.TERM_COUNT_BY_PROJECT,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Count terms linked to a project',
  },
  {
    channel: IPC_CHANNELS.TERM_GET,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Get one term by id',
  },
  {
    channel: IPC_CHANNELS.TERM_UPSERT,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Create or update term',
  },
  {
    channel: IPC_CHANNELS.TERM_REVIEW,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Review actions accept/reject/edit/merge/promote/lock',
  },
  {
    channel: IPC_CHANNELS.TERM_REVIEW_QUEUE,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List DISCOVERED/CANDIDATE terms',
  },
  {
    channel: IPC_CHANNELS.TERM_MATCH_CHAPTER,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Match known terms in chapter text',
  },
  {
    channel: IPC_CHANNELS.TERM_EXTRACT_CANDIDATES,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Extract n-gram candidates (no auto promote)',
  },
  {
    channel: IPC_CHANNELS.TERM_LIST_CANDIDATES,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Pending candidate queue',
  },
  {
    channel: IPC_CHANNELS.TERM_CANDIDATE_REVIEW,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Accept/reject candidates',
  },
  {
    channel: IPC_CHANNELS.TERM_IMPORT,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Import terms CSV/JSON',
  },
  {
    channel: IPC_CHANNELS.TERM_EXPORT,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Export terms CSV/JSON',
  },
  {
    channel: IPC_CHANNELS.CHARACTER_LIST,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List project characters',
  },
  {
    channel: IPC_CHANNELS.CHARACTER_UPSERT,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Create or update character',
  },
  {
    channel: IPC_CHANNELS.RELATIONSHIP_LIST,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List character relationships',
  },
  {
    channel: IPC_CHANNELS.RELATIONSHIP_UPSERT,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Create or update relationship',
  },
  {
    channel: IPC_CHANNELS.MEMORY_STORY_STATE_GET,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Get structured story state',
  },
  {
    channel: IPC_CHANNELS.MEMORY_STORY_STATE_PATCH,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Patch structured story state',
  },
  {
    channel: IPC_CHANNELS.MEMORY_APPLY_DELTA,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Apply validated AI memory delta',
  },
  {
    channel: IPC_CHANNELS.MEMORY_CONFLICT_LIST,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List pending memory conflicts',
  },
  {
    channel: IPC_CHANNELS.MEMORY_CONFLICT_RESOLVE,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Resolve or discard memory conflict',
  },
  {
    channel: IPC_CHANNELS.MEMORY_BUILD_CONTEXT,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Build minimal translation memory context',
  },
  {
    channel: IPC_CHANNELS.PACK_LIST_CHAPTERS,
    permission: 'build_translation_pack',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List chapters for pack builder selection',
  },
  {
    channel: IPC_CHANNELS.PACK_BUILD,
    permission: 'build_translation_pack',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Build minimal TranslationPack prompt preview',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_LIST,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List notebook mappings for project',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_GET,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Get notebook mapping for project+worker',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_PROVISION,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Idempotent NotebookLM provision via Playwright',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_RESUME,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Resume after assisted setup; detect + verify',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_HEALTH,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Notebook knowledge health / versions',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_SYNC_NOW,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Rebuild knowledge + Drive sync → sync_pending',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_REBUILD,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Rebuild local knowledge markdown from SQLite',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_BOOTSTRAP,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Pre-translate knowledge bootstrap + optional seed',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_PREPARE_FOR_TRANSLATE,
    permission: 'manage_notebook',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Prepare Notebook knowledge before Start Translate (best-effort provision)',
  },
  {
    channel: IPC_CHANNELS.TRANSLATE_ENSURE_READY,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Auto-heal worker/Notebook before translate; may open Gemini/Notebook browser',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_RUN_BOOTSTRAP_ANALYSIS,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'One-shot Bootstrap AI analysis (DO NOT TRANSLATE)',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_SKIP_BOOTSTRAP,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Skip AI memory bootstrap; allow translate with partial memory',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_GET_BOOTSTRAP_STATUS,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read bootstrap lifecycle + memory counts',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_RESEARCH_QUERY,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Query Research Notebook for full-novel lookup; may open browser session',
  },
  {
    channel: IPC_CHANNELS.NOTEBOOK_OPEN_RESEARCH,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Open Research Notebook in browser for manual corpus work',
  },
  {
    channel: IPC_CHANNELS.BOOTSTRAP_PACK_NOVEL_CORPUS,
    permission: 'manage_notebook',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Pack SOURCE_READY chapters into NotebookLM-safe NOVEL_PART_*.txt',
  },
  {
    channel: IPC_CHANNELS.BOOTSTRAP_GET_PREPROCESS_PROMPT,
    permission: 'manage_notebook',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Build full-novel preprocess prompt for NotebookLM (00–07)',
  },
  {
    channel: IPC_CHANNELS.BOOTSTRAP_IMPORT_PREPROCESS_RESULT,
    permission: 'manage_notebook',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Parse NotebookLM preprocess response → SQLite → rebuild knowledge',
  },
  {
    channel: IPC_CHANNELS.BOOTSTRAP_SELECT_RESULT_PATH,
    permission: 'manage_notebook',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Open dialog for NotebookLM preprocess response markdown',
  },
  {
    channel: IPC_CHANNELS.BOOTSTRAP_RUN_AUTO_PREPROCESS,
    permission: 'manage_notebook',
    allowsFilesystem: true,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'One-click auto preprocess: Quick bootstrap or full NotebookLM pack/upload/chat/import',
  },
  {
    channel: IPC_CHANNELS.BOOTSTRAP_GET_AUTO_PREPROCESS_PROGRESS,
    permission: 'manage_notebook',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Poll auto-preprocess progress steps',
  },
  {
    channel: IPC_CHANNELS.BOOTSTRAP_RESET_AI_MEMORY,
    permission: 'manage_notebook',
    allowsFilesystem: true,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Wipe project AI memory (confirm) and optionally re-run auto preprocess',
  },
  {
    channel: IPC_CHANNELS.GEMINI_SEND,
    permission: 'send_gemini_translation',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Send TranslationPack via GeminiBrowserProvider; returns raw response',
  },
  {
    channel: IPC_CHANNELS.JOB_LIST,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List translation jobs',
  },
  {
    channel: IPC_CHANNELS.JOB_GET,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Get job + attempt history',
  },
  {
    channel: IPC_CHANNELS.JOB_ATTENTION,
    permission: 'manage_jobs',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Retry / Skip / Manual Fix / Accept With Warning',
  },
  {
    channel: IPC_CHANNELS.JOB_RECOVER,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Mark crashed RUNNING attempts after process interrupt',
  },
  {
    channel: IPC_CHANNELS.JOB_ENQUEUE,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Enqueue durable translation job',
  },
  {
    channel: IPC_CHANNELS.JOB_ENQUEUE_NOVEL,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Enqueue one translate job per eligible chapter (full novel / range)',
  },
  {
    channel: IPC_CHANNELS.JOB_CANCEL,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Cancel job',
  },
  {
    channel: IPC_CHANNELS.JOB_RETRY,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Requeue failed job',
  },
  {
    channel: IPC_CHANNELS.JOB_BULK,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Bulk cancel / delete / retry selected jobs',
  },
  {
    channel: IPC_CHANNELS.JOB_MOVE,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Change job priority',
  },
  {
    channel: IPC_CHANNELS.JOB_CHANGE_WORKER,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'PINNED / POOL worker assignment',
  },
  {
    channel: IPC_CHANNELS.JOB_PAUSE_ALL,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Pause all queued jobs',
  },
  {
    channel: IPC_CHANNELS.JOB_RESUME_ALL,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Resume paused jobs',
  },
  {
    channel: IPC_CHANNELS.JOB_SCHEDULER_STATUS,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Scheduler running/paused/inFlight + concurrency policy',
  },
  {
    channel: IPC_CHANNELS.JOB_SCHEDULER_UPDATE_SETTINGS,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Update concurrency policy (global / per-project / per-provider)',
  },
  {
    channel: IPC_CHANNELS.JOB_WORKERS,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List worker health',
  },
  {
    channel: IPC_CHANNELS.LEARNING_DASHBOARD,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Learning dashboard: candidates, conflicts, promotions, memories',
  },
  {
    channel: IPC_CHANNELS.EDITOR_GET_CHAPTER,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Load chapter paragraphs + translations for split editor',
  },
  {
    channel: IPC_CHANNELS.EDITOR_SAVE_PARAGRAPH,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Save human edit (HUMAN_EDIT, human_locked)',
  },
  {
    channel: IPC_CHANNELS.EDITOR_LIST_VERSIONS,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List translation version history',
  },
  {
    channel: IPC_CHANNELS.EDITOR_REVERT_VERSION,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Revert translation to prior version',
  },
  {
    channel: IPC_CHANNELS.EDITOR_GET_CONTEXT,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Editor context panel: characters, relationships, terms, memory',
  },
  {
    channel: IPC_CHANNELS.EDITOR_CLEAR_CHAPTER_TRANSLATIONS,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Clear AI translations for chapter; keep human_locked',
  },
  {
    channel: IPC_CHANNELS.EDITOR_CLEAR_CHAPTERS_TRANSLATIONS,
    permission: 'manage_memory',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Clear AI translations for multiple chapters; keep human_locked',
  },
  {
    channel: IPC_CHANNELS.EDITOR_RETRANSLATE_CHAPTER,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Clear AI chapter translations then enqueue translate job',
  },
  {
    channel: IPC_CHANNELS.EDITOR_RETRANSLATE_CHAPTERS,
    permission: 'manage_jobs',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Clear AI translations for multiple chapters then enqueue translate jobs',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_EXPORT_NOVEL,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Export translated novel TXT/DOCX/EPUB',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SELECT_EXPORT_PATH,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Save dialog for export path',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_CREATE_BACKUP,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Create full or project backup archive',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_PREVIEW_RESTORE,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Validate backup archive before restore',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_RESTORE_BACKUP,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Restore backup archive (requires confirmOverwrite)',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_GET_AUTO_BACKUP,
    permission: 'export',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read auto-backup schedule config',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SET_AUTO_BACKUP,
    permission: 'export',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Update auto-backup schedule config',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_LIST_BACKUPS,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'List local backup files',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_CREATE_MANUAL_BACKUP,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Create manual DB snapshot',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SELECT_BACKUP_PATH,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Open dialog for .nts-project.zip restore',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_GET_BACKUP_DIRECTORY,
    permission: 'export',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read custom backup directory setting',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SET_BACKUP_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Set custom backup directory under user control',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SELECT_BACKUP_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Folder picker for custom backup directory',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_RESOLVE_EXPORT_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Resolve project/global export directory without writing files',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_GET_DEFAULT_EXPORT_DIRECTORY,
    permission: 'export',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read global default export directory setting',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SET_DEFAULT_EXPORT_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Set global default export directory',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SELECT_EXPORT_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Folder picker for export directory configuration',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_GET_PROJECT_EXPORT_SETTINGS,
    permission: 'export',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read project export directory override settings',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SET_PROJECT_EXPORT_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Set project-specific export directory override',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_PERSIST_EXPORT_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Persist first-time export directory pick (project or global scope)',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_OPEN_DEFAULT_EXPORT_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Open configured global default export directory',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_OPEN_EXPORT_DIRECTORY,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Open resolved export directory via shell.openPath',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_OPEN_EXPORTED_FILE,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Open exported file only when path is under resolved export directory',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_EXPORT_CHAPTER,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Export single chapter to resolved export directory (atomic write)',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_EXPORT_CHAPTER_RANGE,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Export chapter range to resolved export directory',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_SETUP_STORAGE_ROOT,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'One-shot storage root: Exports + Backups subfolders',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_CHECK_STORAGE_HEALTH,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Check export/backup directory writability for Storage tab',
  },
  {
    channel: IPC_CHANNELS.PORTABILITY_BACKUP_NOW,
    permission: 'export',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Manual full backup from Storage tab',
  },
  {
    channel: IPC_CHANNELS.TERM_PREVIEW_IMPORT,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Preview term import with duplicate detection',
  },
  {
    channel: IPC_CHANNELS.TERM_COMMIT_IMPORT,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Commit term import with duplicate strategy',
  },
  {
    channel: IPC_CHANNELS.TABULAR_SELECT_IMPORT_FILE,
    permission: 'manage_terms',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Open dialog for CSV/XLSX tabular import',
  },
  {
    channel: IPC_CHANNELS.TABULAR_PREVIEW,
    permission: 'manage_terms',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Parse and preview tabular import',
  },
  {
    channel: IPC_CHANNELS.TABULAR_COMMIT,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Commit tabular import in transaction',
  },
  {
    channel: IPC_CHANNELS.TABULAR_DISCARD_PREVIEW,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Discard tabular import preview session',
  },
  {
    channel: IPC_CHANNELS.TABULAR_SELECT_EXPORT_PATH,
    permission: 'manage_terms',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Save dialog for tabular export',
  },
  {
    channel: IPC_CHANNELS.TABULAR_EXPORT,
    permission: 'manage_terms',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Export terms/characters to CSV or XLSX',
  },
  {
    channel: IPC_CHANNELS.TABULAR_UNDO_LAST,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Undo last tabular import batch',
  },
  {
    channel: IPC_CHANNELS.TABULAR_LIST_HISTORY,
    permission: 'manage_terms',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List tabular import history',
  },
  {
    channel: IPC_CHANNELS.TABULAR_DOWNLOAD_TERM_TEMPLATE,
    permission: 'manage_terms',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Download Term Vault sample XLSX template',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_LIST_PROVIDERS,
    permission: 'manage_diagnostics',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List automation provider versions + last success',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_HEALTH_REPORT,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Build automation health report',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_EXPORT,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Export sanitized diagnostics ZIP (no secrets)',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_CONNECTION_TEST,
    permission: 'manage_diagnostics',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Test Gemini/Notebook/Drive/browser profile connection',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_AI_BROWSER_PROBE,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Stepwise AI browser diagnostics; trial translate skips Project Memory',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_GOOGLE_SMOKE,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Opt-in Real Google smoke A–H; smoke notebook only; writes REAL_GOOGLE_TEST_REPORT.md',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_NOTEBOOK_GROUNDING_SMOKE,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes:
      'Opt-in Real Notebook grounding A–D; smoke notebook only; writes REAL_NOTEBOOK_GROUNDING_REPORT.md; no cookies/tokens in report',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_GET_OVERRIDES,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Read local selector override JSON',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_LOAD_OVERRIDES,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Load + validate selector override JSON (data only)',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_SAVE_OVERRIDES,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Save validated selector override JSON',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_RELOAD_OVERRIDES,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Reload selector overrides from disk without rebuild',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_REPAIR_START,
    permission: 'manage_diagnostics',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Start interactive selector repair (headed browser)',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_REPAIR_CAPTURE,
    permission: 'manage_diagnostics',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Capture clicked element locator suggestion',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_REPAIR_APPLY,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Apply suggested locator to override JSON',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_REPAIR_CANCEL,
    permission: 'manage_diagnostics',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Cancel interactive repair session',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_SELECT_EXPORT_PATH,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Save dialog for diagnostics ZIP',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_SELECT_OVERRIDE_PATH,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Open dialog for selector override JSON',
  },
  {
    channel: IPC_CHANNELS.DIAGNOSTICS_RUN_SYSTEM_HEALTH,
    permission: 'manage_diagnostics',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Orchestrated system health check for Advanced settings',
  },
  {
    channel: IPC_CHANNELS.SETUP_GET_STATUS,
    permission: 'manage_setup',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read first-run setup wizard status',
  },
  {
    channel: IPC_CHANNELS.SETUP_SET_STEP,
    permission: 'manage_setup',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Advance first-run setup wizard step',
  },
  {
    channel: IPC_CHANNELS.SETUP_EXPLORE,
    permission: 'manage_setup',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Defer onboarding without marking setup complete',
  },
  {
    channel: IPC_CHANNELS.SETUP_COMPLETE,
    permission: 'manage_setup',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Mark first-run setup complete',
  },
  {
    channel: IPC_CHANNELS.APP_CHECK_FOR_UPDATES,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Check for updates via UpdateProvider (placeholder if no server)',
  },
  {
    channel: IPC_CHANNELS.UPDATE_GET_STATUS,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Read Squirrel/update provider status for settings UI',
  },
  {
    channel: IPC_CHANNELS.UPDATE_CHECK_NOW,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Manual update check — network to update feed only',
  },
  {
    channel: IPC_CHANNELS.UPDATE_INSTALL_AND_RESTART,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Apply downloaded update and restart via Electron autoUpdater',
  },
  {
    channel: IPC_CHANNELS.UPDATE_POSTPONE,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Snooze update prompt until timestamp',
  },
  {
    channel: IPC_CHANNELS.UPDATE_STATUS,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Main→renderer update status push event',
  },
  {
    channel: IPC_CHANNELS.LOGS_TAIL,
    permission: 'read_app_info',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Read redacted application log tail for UI log viewer',
  },
  {
    channel: IPC_CHANNELS.LOGS_OPEN_DIR,
    permission: 'read_app_info',
    allowsFilesystem: true,
    allowsShell: true,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Open managed logs directory in OS file manager',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_LIST,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List AI providers + worker install status (no secrets)',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_HEALTH,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'AI provider health monitor',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_SET_PRIORITY,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Update AI provider priority',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_SET_ENABLED,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Enable/disable AI provider',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_CHECK,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Run AI provider health check now',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_SET_FALLBACK,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Configure AI provider fallback policy',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_GET_ROUTING,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read primary translation provider routing config',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_SET_PRIMARY,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Set global primary translation AI provider and fallback order',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_SET_PREFERENCE,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Set global AI routing preference (provider order / policy)',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_CHECK_ALL,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Health-check all enabled AI providers',
  },
  {
    channel: IPC_CHANNELS.AI_PROVIDER_INSTALL_WORKER,
    permission: 'manage_ai_providers',
    allowsFilesystem: true,
    allowsShell: true,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Create Python venv + pip install gemini worker deps',
  },
  {
    channel: IPC_CHANNELS.AI_ACCOUNT_LIST,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List AI accounts metadata (no cookies)',
  },
  {
    channel: IPC_CHANNELS.AI_ACCOUNT_CREATE,
    permission: 'manage_ai_providers',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Create AI account + session directory',
  },
  {
    channel: IPC_CHANNELS.AI_ACCOUNT_PASTE_COOKIES,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Accept PSID cookies once; encrypt via safeStorage; never return plaintext',
  },
  {
    channel: IPC_CHANNELS.AI_ACCOUNT_CHECK,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Re-check AI account session via worker',
  },
  {
    channel: IPC_CHANNELS.AI_ACCOUNT_DISABLE,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Disable AI account',
  },
  {
    channel: IPC_CHANNELS.AI_ACCOUNT_DELETE,
    permission: 'manage_ai_providers',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Delete AI account, session dir, encrypted secret',
  },
  {
    channel: IPC_CHANNELS.AI_BROWSER_ACCOUNT_OPEN_LOGIN,
    permission: 'manage_ai_providers',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Open headed Playwright for ChatGPT/Meta AI profile login',
  },
  {
    channel: IPC_CHANNELS.AI_BROWSER_ACCOUNT_VERIFY,
    permission: 'manage_ai_providers',
    allowsFilesystem: true,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Verify ChatGPT/Meta AI browser session; update account status',
  },
  {
    channel: IPC_CHANNELS.AI_ACCOUNT_UPDATE_DISPLAY_NAME,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Rename ChatGPT/Meta AI browser account display name',
  },
  {
    channel: IPC_CHANNELS.AI_MODELS_LIST,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'List AI models for provider',
  },
  {
    channel: IPC_CHANNELS.AI_MODELS_SYNC,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Sync model catalog from Gemini Web API worker',
  },
  {
    channel: IPC_CHANNELS.AI_AUTO_SETUP_STATUS,
    permission: 'manage_ai_providers',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Novice AI tab readiness snapshot (no secrets)',
  },
  {
    channel: IPC_CHANNELS.AI_AUTO_SETUP_RUN,
    permission: 'manage_ai_providers',
    allowsFilesystem: true,
    allowsShell: true,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'One-click AI check/fix: provider order, worker, Gemini probe',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_GET_ACCESS_STATE,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Sanitized Khepree access state — no tokens',
  },
  {
    channel: IPC_CHANNELS.UI_LANGUAGE_GET,
    permission: 'manage_setup',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Read UI language from app_meta',
  },
  {
    channel: IPC_CHANNELS.UI_LANGUAGE_SET,
    permission: 'manage_setup',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'Persist UI language preference in app_meta',
  },
  {
    channel: IPC_CHANNELS.UI_LANGUAGE_COMPLETE_FIRST_RUN,
    permission: 'manage_setup',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: true,
    allowsSecrets: noSecrets,
    notes: 'First-run language chooser — app_meta before login',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_START_LOGIN,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Opens Khepree browser login — no password IPC',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_RETRY_COLD_START,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Retry online cold-start validation',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_RETRY_ACTIVATION,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Retry device activation after slot freed',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_REFRESH_ENTITLEMENT,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Poll entitlement after checkout',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_START_CHECKOUT,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Open Khepree hosted checkout in system browser — no payment secrets to renderer',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_CANCEL_CHECKOUT,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Cancel in-app checkout polling',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_CHECK_CHECKOUT,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Manual checkout status check after browser payment',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_REOPEN_CHECKOUT,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Re-open validated checkout URL if still safe',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_GET_PLAN_CATALOG,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Sanitized plan catalog from Khepree API',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_SIGN_OUT,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Clear Khepree session credentials',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_OPEN_EXTERNAL,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: true,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Open allowlisted Khepree URL only',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_ANNOUNCEMENTS_LIST,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'List sanitized Khepree system announcements for notification center',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_ANNOUNCEMENTS_SYNC,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Manual sync of Khepree announcements from API',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_ANNOUNCEMENT_MARK_READ,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Persist local read state for a Khepree announcement',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_ANNOUNCEMENT_DISMISS,
    permission: 'read_app_info',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Persist local dismiss state for a Khepree announcement',
  },
  {
    channel: IPC_CHANNELS.KHEPREE_ACCESS_STATE,
    permission: 'manage_khepree_access',
    allowsFilesystem: false,
    allowsShell: false,
    allowsDbQuery: false,
    allowsSecrets: noSecrets,
    notes: 'Main→renderer access state push event',
  },
] as const;

export function assertIpcAuditComplete(): void {
  const audited = new Set(IPC_CHANNEL_AUDIT.map((entry) => entry.channel));
  for (const channel of Object.values(IPC_CHANNELS)) {
    if (!audited.has(channel)) {
      throw new Error(`IPC channel missing from security audit: ${channel}`);
    }
  }
}
